color_theme = "catppuccin_mocha"
theme_background = false
truecolor = true
force_tty = true
selected_bg = 45
selected_fg = 15
proc_on_start = false
proc_tree = true
proc_colors = true
proc_gradient = true
proc_per_core = true
proc_mem_bytes = true
proc_info_cpu = true
proc_info_mem = true
proc_info_cmd = true
proc_filter_kernel = false
proc_diacritics = false
proc_reversed = false
proc_sorting = "cpu lazy"
proc_sorting_asc = false
proc_show_self = true
proc_show_forward = false
proc_command = true
proc_verbose = false
preserve_aspect_ratio = false
show_clock = true
clock_format = "%X"
base_10_sizes = false
show_arrows = false
show_battery = true
show_uptime = true
show_pid = true
show_os = true
check_updates = true
update_check_interval = 24
